name: Deploy Frontend Site to GitHub Pages

on:
  push:
    branches: ["master"] # 如果你的主分支是 main，请改为 "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 建议使用稳定的 LTS 版本，如 18 或 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build # 这一步会将你的源码编译成 dist 目录下的 HTML/CSS/JS

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # ⚠️注意：确保这里是你本地执行 build 后生成的文件夹名称（通常是 dist 或 build）

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5